name: "On comment test workflow"

on:
  push:
    branches: ["main", "**"]

  pull_request:
    branches: ["main", "**"]
    types: [opened, synchronize, reopened]

  issue_comment:
    types: [created]

permissions:
  id-token: write
  contents: read
  issues: read
  pull-requests: read

jobs:
  react-to-comment:
    if: github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/test_comment')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: print event json
        run: echo "${{ tojson(github.event) }}"
      - uses: jwalton/gh-find-current-pr@master
        id: findPr
        with:
          state: all
      - name: Post comment about triggered action
        if: success() && steps.findPr.outputs.number
        env:
          PR_NUMBER: ${{ steps.findPr.outputs.pr }}
        run: |
          echo "${PR_NUMBER}"
      - name: Post a comment
        run: |
          set -x
          COMMENT_URL="${{ github.event.issue.comments_url }}"
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/vnd.github+json" \
          -d "{\"body\": \"Action triggered by comment: ${{ github.event.comment.body }}: [View logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\"}" \
          $COMMENT_URL


