name: "On comment test"

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  issue_comment:
    types: [created]


jobs:
  react-to-comment:
    if: if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/test_comment')
  run: |
    echo "Triggered by comment"
