name: "On comment test workflow"

on:
  push:
    branches: ["main", "**"]

  pull_request:
    branches: ["main", "**"]
    types: [opened, synchronize, reopened]

  issue_comment:
    types: [created]

permissions:
  id-token: write
  contents: read
  issues: read
  pull-requests: write

jobs:
  print-github-event-json:
    runs-on: ubuntu-latest
    steps:
      - name: Print event JSON
        run: echo "${{ tojson(github.event) }}"

  post-comment:
    runs-on: "ubuntu-latest"
    if: |
      github.event_name == 'issue_comment' &&
      (
        startsWith(github.event.comment.body, '/build') ||
        startsWith(github.event.comment.body, '/test')
      )
    uses: .github/workflows/post-pr-comment.yaml
    with:
      comment: "Action triggered by comment: ${{ github.event.comment.body }}: [View logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
    secrets: inherit
